### ISSUE TITLE
Add relationship filter criteria

### ISSUE THREAD

**Issue by zarathustra323** [as3io/modlr#78]
Example:

```
tags:
    type: many
    entity: tag
    inverse: true
    field: family
    filter: "{parent: {$exists: false}}"
```

Would prevent showing tags that are children.
